project_id = "council-ci"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
auto_expose_new_tables = true

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.seed]
enabled = false

[db.pooler]
enabled = false

[auth]
enabled = true
site_url = "http://127.0.0.1:3105"
additional_redirect_urls = []

[realtime]
enabled = false

[studio]
enabled = false

[local_smtp]
enabled = false

[storage]
enabled = false

[analytics]
enabled = false

[edge_runtime]
enabled = false
