import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  wrapper: {
    display: "flex",
    height: "100dvh",
    position: "relative",
    overflow: "hidden",
    background: "radial-gradient(circle at 15% 0%, color-mix(in srgb, var(--color-secondary) 14%, transparent), transparent 32%), radial-gradient(circle at 90% 100%, color-mix(in srgb, #7aa2ff 10%, transparent), transparent 34%), var(--color-background)",
  },

  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0, 0, 0, 0.4)",
    backdropFilter: "blur(2px)",
    WebkitBackdropFilter: "blur(2px)",
    zIndex: 20,
  },

  sidebar: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    width: 280,
    background: "color-mix(in srgb, var(--color-surface) 94%, transparent)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    borderLeft: "1px solid var(--color-border)",
    zIndex: 30,
    display: "flex",
    flexDirection: "column",
    transition: "transform 0.25s cubic-bezier(0.23, 1, 0.32, 1)",
  },

  sidebarDesktop: {
    order: 2,
    background: "color-mix(in srgb, var(--color-surface) 88%, transparent)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    borderLeft: "1px solid var(--color-border)",
    display: "flex",
    flexDirection: "column",
    height: "100dvh",
    overflow: "hidden",
    transition: "width 0.25s cubic-bezier(0.23, 1, 0.32, 1), min-width 0.25s cubic-bezier(0.23, 1, 0.32, 1)",
  },

  notesPanel: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    width: 280,
    background: "color-mix(in srgb, var(--color-surface) 94%, transparent)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    borderLeft: "1px solid var(--color-border)",
    zIndex: 30,
    display: "flex",
    flexDirection: "column",
    transition: "transform 0.25s cubic-bezier(0.23, 1, 0.32, 1)",
  },
  notesPanelDesktop: {
    order: 1,
    background: "color-mix(in srgb, var(--color-surface) 88%, transparent)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    borderLeft: "1px solid var(--color-border)",
    display: "flex",
    flexDirection: "column",
    height: "100dvh",
    overflow: "hidden",
    transition: "width 0.25s cubic-bezier(0.23, 1, 0.32, 1), min-width 0.25s cubic-bezier(0.23, 1, 0.32, 1)",
  },
  notesList: {
    flex: 1,
    overflowY: "auto",
    padding: "8px 10px",
  },
  noteItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "9px 10px",
    borderRadius: 8,
  },
  noteCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 5,
    border: "1.5px solid var(--color-text-muted)",
    background: "transparent",
    cursor: "pointer",
    flexShrink: 0,
    marginTop: 1,
    padding: 0,
  },
  noteInfo: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  noteTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: "var(--color-text-primary)",
    lineHeight: 1.35,
    overflowWrap: "anywhere",
  },
  noteDesc: {
    fontSize: 12,
    color: "var(--color-text-muted)",
    lineHeight: 1.35,
  },
  noteDue: {
    fontSize: 11,
    fontWeight: 500,
    color: "var(--color-primary)",
  },
  noteBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    minWidth: 15,
    height: 15,
    padding: "0 3px",
    borderRadius: 8,
    background: "var(--color-primary)",
    color: "var(--color-primary-foreground)",
    fontSize: 9.5,
    fontWeight: 700,
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 16px",
    height: 69,
    borderBottom: "1px solid var(--color-border)",
  },
  sidebarTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "var(--color-text-primary)",
  },
  closeBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    display: "flex",
  },
  newChatBtn: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    margin: "12px 12px 8px",
    padding: "10px 14px",
    background: "var(--color-primary)",
    color: "var(--color-primary-foreground)",
    border: "none",
    borderRadius: "var(--radius-md)",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 500,
    fontFamily: "var(--font-family)",
  },
  conversationList: {
    flex: 1,
    overflowY: "auto",
    padding: "4px 8px",
  },
  noConversations: {
    textAlign: "center",
    color: "var(--color-text-muted)",
    fontSize: 13,
    padding: "20px 0",
  },
  conversationItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    width: "100%",
    padding: "10px 12px",
    background: "transparent",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    textAlign: "left",
    color: "var(--color-text-primary)",
    fontSize: 13,
    fontFamily: "var(--font-family)",
    transition: "background 0.15s ease",
  },
  conversationItemActive: {
    background: "var(--color-background)",
  },
  conversationInfo: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  conversationTitle: {
    fontSize: 13,
    fontWeight: 500,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  conversationTime: {
    fontSize: 11,
    color: "var(--color-text-muted)",
  },
  deleteBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    color: "var(--color-text-muted)",
    opacity: 0.5,
    flexShrink: 0,
    display: "flex",
  },
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100dvh",
    flex: 1,
    background: "transparent",
    width: "100%",
    position: "relative",
  },

  containerDesktop: {
    display: "flex",
    flexDirection: "column",
    height: "100dvh",
    flex: 1,
    background: "transparent",
    width: "100%",
    position: "relative",
  },

  header: {
    position: "sticky",
    top: 0,
    zIndex: 10,
    background: "color-mix(in srgb, var(--color-background) 82%, transparent)",
    backdropFilter: "blur(18px) saturate(1.15)",
    WebkitBackdropFilter: "blur(18px) saturate(1.15)",
    borderBottom: "1px solid color-mix(in srgb, var(--color-border) 80%, transparent)",
  },
  headerContent: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "12px 16px 12px 26px",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  headerCenter: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    flexShrink: 1,

    marginLeft: 16,
    paddingLeft: 26,
    borderLeft: "1px solid var(--color-border)",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
    padding: 3,
    borderRadius: 999,
    background: "color-mix(in srgb, var(--color-surface) 80%, transparent)",
    border: "1px solid color-mix(in srgb, var(--color-border) 70%, transparent)",
  },
  headerNavRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 12px 8px",
  },
  headerSelectorsRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 12px 10px",
  },

  logoMark: {
    width: 46,
    height: 36,
    flexShrink: 0,
    backgroundColor: "var(--color-text-primary)",
    WebkitMaskImage: "url('/zuychin-logo.svg')",
    maskImage: "url('/zuychin-logo.svg')",
    WebkitMaskRepeat: "no-repeat",
    maskRepeat: "no-repeat",
    WebkitMaskPosition: "center",
    maskPosition: "center",
    WebkitMaskSize: "contain",
    maskSize: "contain",
  },

  logoMarkMobile: {
    width: 35,
    height: 27,
    flexShrink: 0,
    backgroundColor: "var(--color-text-primary)",
    WebkitMaskImage: "url('/zuychin-logo.svg')",
    maskImage: "url('/zuychin-logo.svg')",
    WebkitMaskRepeat: "no-repeat",
    maskRepeat: "no-repeat",
    WebkitMaskPosition: "center",
    maskPosition: "center",
    WebkitMaskSize: "contain",
    maskSize: "contain",
  },
  brandText: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flexShrink: 0,
  },
  brandTextMobile: {
    display: "flex",
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
    minWidth: 0,
  },
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    flexShrink: 0,
    transition: "background 0.15s ease",
  },
  title: {
    fontSize: 17,
    fontWeight: 600,
    letterSpacing: "-0.3px",
    color: "var(--color-text-primary)",
    lineHeight: 1.1,
  },
  subtitle: {
    fontSize: 12,
    fontWeight: 500,
    color: "var(--color-text-muted)",
    letterSpacing: "0.2px",
  },

  subtitleMobile: {
    fontSize: 17,
    fontWeight: 500,
    color: "var(--color-text-muted)",
    letterSpacing: "-0.2px",
  },
  modelControlCluster: {
    position: "relative",
    display: "flex",
    alignItems: "stretch",
    minWidth: 0,
    // Tracks its row like the nav row above it. A fixed cap here left the
    // selector at 360px on wide screens while everything around it filled out.
    maxWidth: "none",
    flex: 1,
    padding: 2,
    gap: 2,
    borderRadius: 12,
    background: "color-mix(in srgb, var(--color-surface) 60%, var(--color-background))",
    border: "1px solid color-mix(in srgb, var(--color-border) 78%, transparent)",
  },
  modelClusterButton: {
    width: 34,
    minWidth: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    border: "none",
    borderRadius: 9,
    cursor: "pointer",
    color: "var(--color-text-muted)",
    background: "color-mix(in srgb, var(--color-background) 52%, transparent)",
    transition: "background 0.15s ease, color 0.15s ease",
  },
  modelClusterButtonActive: {
    color: "var(--color-primary)",
    background: "color-mix(in srgb, var(--color-primary) 11%, var(--color-background))",
  },
  modelSettingsPopover: {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    zIndex: 45,
    width: "min(320px, calc(100vw - 24px))",
    padding: "13px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    borderRadius: 14,
    background: "color-mix(in srgb, var(--color-surface) 84%, var(--color-background))",
    border: "1px solid color-mix(in srgb, var(--color-border) 82%, transparent)",
    boxShadow: "0 14px 34px rgba(0,0,0,0.16)",
  },
  infoBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    flexShrink: 0,
    transition: "background 0.15s ease",
  },
  graphBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 11px",
    fontSize: 12.5,
    fontWeight: 500,
    borderRadius: 10,
    border: "1px solid var(--color-border)",
    background: "var(--color-surface)",
    color: "var(--color-text-primary)",
    textDecoration: "none",
    flexShrink: 0,
    transition: "background 0.15s ease",
  },

  messages: {
    flex: 1,
    overflowY: "auto",
    padding: "20px 24px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    maxWidth: 820,
    width: "100%",
    margin: "0 auto",
  },

  emptyState: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "0 16px",
  },
  suggestionRow: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    marginTop: 18,
    maxWidth: 520,
  },
  suggestionChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "9px 14px",
    fontSize: 13,
    fontWeight: 550,
    fontFamily: "var(--font-family)",
    color: "var(--color-text-primary)",
    background: "color-mix(in srgb, var(--color-surface) 88%, transparent)",
    border: "1px solid var(--color-border)",
    borderRadius: 999,
    cursor: "pointer",
    boxShadow: "0 4px 18px rgba(0, 0, 0, 0.06)",
    transition: "background 0.15s ease, transform 0.15s ease",
  },
  suggestionIcon: {
    display: "flex",
    alignItems: "center",
    color: "var(--color-text-muted)",
  },
  emptyHint: {
    marginTop: 16,
    fontSize: 12,
    color: "var(--color-text-muted)",
    textAlign: "center",
    lineHeight: 1.6,
  },
  todayCard: {
    width: "100%",
    maxWidth: 520,
    marginTop: 18,
    padding: "16px 18px",
    textAlign: "left",
    background: "color-mix(in srgb, var(--color-surface) 88%, transparent)",
    border: "1px solid var(--color-border)",
    borderRadius: 16,
    boxShadow: "0 4px 18px rgba(0, 0, 0, 0.06)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  todayHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  todayTitle: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    fontSize: 13.5,
    fontWeight: 650,
    color: "var(--color-text-primary)",
  },
  todayDismiss: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 24,
    height: 24,
    border: "none",
    background: "transparent",
    color: "var(--color-text-muted)",
    cursor: "pointer",
    borderRadius: 6,
  },
  todaySectionLabel: {
    fontSize: 11,
    fontWeight: 650,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "var(--color-text-muted)",
  },
  todayItem: {
    display: "flex",
    gap: 7,
    alignItems: "baseline",
    fontSize: 13,
    color: "var(--color-text-primary)",
    lineHeight: 1.5,
  },
  todayItemMeta: {
    marginLeft: "auto",
    paddingLeft: 8,
    fontSize: 11.5,
    color: "var(--color-text-muted)",
    whiteSpace: "nowrap",
  },
  hintKbd: {
    padding: "1px 6px",
    borderRadius: 6,
    fontSize: 11.5,
    fontFamily: "var(--font-mono)",
    background: "color-mix(in srgb, var(--color-surface) 90%, transparent)",
    border: "1px solid var(--color-border)",
  },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: "var(--color-primary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: "var(--color-text-primary)",
  },
  emptySubtitle: {
    fontSize: 14,
    color: "var(--color-text-muted)",
  },

  messageBubbleWrapper: {
    display: "flex",
    alignItems: "flex-end",
    gap: 8,
  },
  msgAvatar: {
    width: 24,
    height: 24,
    borderRadius: "50%",
    background: "var(--color-primary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  userAvatar: {
    background: "var(--color-surface)",
  },
  bubble: {
    maxWidth: "78%",
    padding: "10px 14px",
    borderRadius: "var(--radius-md)",
    lineHeight: 1.45,
  },
  userBubble: {
    background: "var(--color-primary)",
    color: "var(--color-primary-foreground)",
    borderBottomRightRadius: 4,
  },
  aiBubble: {
    background: "var(--color-bubble-ai)",
    color: "var(--color-text-primary)",
    borderBottomLeftRadius: 4,
  },
  bubbleText: {
    fontSize: 15,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },

  typingRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    padding: "4px 2px",
  },
  typingDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "var(--color-text-muted)",
  },
  typingLabel: {
    fontSize: 12,
    color: "var(--color-text-muted)",
    marginLeft: 6,
  },

  footer: {
    position: "sticky",
    bottom: 0,
    background: "transparent",
    padding: "14px 24px calc(env(safe-area-inset-bottom, 0px) + 14px)",
    maxWidth: 820,
    width: "100%",
    margin: "0 auto",
  },

  filePreview: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: "var(--color-surface)",
    borderRadius: 8,
    padding: "8px 12px",
    marginBottom: 8,
  },
  filePreviewInfo: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: "var(--color-text-primary)",
    fontSize: 13,
    minWidth: 0,
  },
  filePreviewName: {
    fontWeight: 500,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  filePreviewSize: {
    color: "var(--color-text-muted)",
    fontSize: 12,
    flexShrink: 0,
  },
  filePreviewRemove: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    color: "var(--color-text-muted)",
    display: "flex",
    flexShrink: 0,
  },

  replyPreview: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "var(--color-surface)",
    borderLeft: "3px solid var(--color-primary)",
    borderRadius: 8,
    padding: "8px 12px",
    marginBottom: 8,
  },
  replyPreviewLabel: {
    color: "var(--color-primary)",
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
  },
  replyPreviewText: {
    color: "var(--color-text-muted)",
    fontSize: 12.5,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    flex: 1,
    minWidth: 0,
  },
  replyQuote: {
    display: "block",
    borderLeft: "2px solid var(--color-primary)",
    borderRadius: 4,
    background: "color-mix(in srgb, var(--color-primary) 8%, transparent)",
    padding: "5px 9px",
    marginBottom: 7,
    fontSize: 12.5,
  },
  replyQuoteRole: {
    display: "block",
    fontWeight: 600,
    fontSize: 11,
    color: "var(--color-primary)",
    marginBottom: 2,
  },
  replyQuoteText: {
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    color: "var(--color-text-muted)",
    wordBreak: "break-word",
  },
  replyMsgBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    display: "flex",
    alignSelf: "flex-end",
    marginBottom: 4,
    color: "var(--color-text-muted)",
    opacity: 0.45,
    flexShrink: 0,
  },

  fileTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 8px",
    borderRadius: 6,
    background: "rgba(255,255,255,0.15)",
    marginBottom: 6,
    fontSize: 12,
  },
  fileTagName: {
    fontWeight: 500,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 180,
  },

  inputRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "color-mix(in srgb, var(--color-surface) 92%, transparent)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    border: "1px solid color-mix(in srgb, var(--color-border) 85%, transparent)",
    borderRadius: 999,
    padding: "10px 10px 10px 18px",
    boxShadow: "0 10px 40px rgba(0, 0, 0, 0.12)",
  },
  attachBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    display: "flex",
    alignItems: "center",
    flexShrink: 0,
  },
  textarea: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    fontSize: 15,
    fontFamily: "var(--font-family)",
    color: "var(--color-text-primary)",
    resize: "none",
    lineHeight: 1.4,
    paddingTop: 6,
    paddingBottom: 6,
  },
  sendButton: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    background: "var(--color-primary)",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "opacity 0.15s ease",
    flexShrink: 0,
    boxShadow: "0 4px 14px rgba(0, 0, 0, 0.18)",
  },

  msgMeta: {
    marginTop: 8,
    fontSize: 10.5,
    color: "var(--color-text-muted)",
    letterSpacing: 0.1,
  },

  scrollDownBtn: {
    position: "absolute",
    left: "50%",
    transform: "translateX(-50%)",
    bottom: 96,
    zIndex: 9,
    width: 36,
    height: 36,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "color-mix(in srgb, var(--color-surface) 94%, transparent)",
    color: "var(--color-text-primary)",
    border: "1px solid var(--color-border)",
    boxShadow: "0 8px 26px rgba(0, 0, 0, 0.2)",
    cursor: "pointer",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  },

  convSkeleton: {
    height: 46,
    margin: "6px 4px",
    borderRadius: 10,
    background: "color-mix(in srgb, var(--color-text-muted) 14%, transparent)",
  },

  exportRow: {
    display: "flex",
    gap: 6,
    marginTop: 8,
    paddingTop: 8,
    borderTop: "1px solid var(--color-border)",
  },
  exportBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "4px 10px",
    fontSize: 11,
    fontWeight: 500,
    fontFamily: "var(--font-family)",
    color: "var(--color-text-muted)",
    background: "var(--color-background)",
    border: "1px solid var(--color-border)",
    borderRadius: 6,
    cursor: "pointer",
    transition: "background 0.15s ease, color 0.15s ease, border-color 0.15s ease",
  },
  // Expanded state of the Generate toggle.
  exportBtnActive: {
    color: "var(--color-primary)",
    border: "1px solid color-mix(in srgb, var(--color-primary) 45%, var(--color-border))",
    background: "color-mix(in srgb, var(--color-primary) 10%, var(--color-background))",
  },

  artifactRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  artifactChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    fontSize: 13,
    fontWeight: 500,
    fontFamily: "var(--font-family)",
    color: "var(--color-text-primary)",
    background: "var(--color-surface)",
    border: "1px solid var(--color-primary)",
    borderRadius: 8,
    cursor: "pointer",
    textDecoration: "none",
    maxWidth: "100%",
  },
  artifactName: {
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 220,
  },
  artifactSize: {
    fontSize: 11,
    color: "var(--color-text-muted)",
  },

  agentTracker: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 220,
  },
  agentHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--color-text-primary)",
  },
  agentSteps: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    marginTop: 2,
  },
  agentStep: {
    display: "flex",
    alignItems: "flex-start",
    gap: 6,
    fontSize: 12.5,
    color: "var(--color-text-primary)",
  },
  agentStepMark: {
    color: "var(--color-primary)",
    width: 12,
    flexShrink: 0,
  },
  agentLine: {
    fontSize: 11.5,
    color: "var(--color-text-muted)",
    fontStyle: "italic",
  },

  cmdMenu: {
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: 14,
    padding: 6,
    marginBottom: 10,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    maxHeight: 280,
    overflowY: "auto",
    boxShadow: "0 6px 24px rgba(0,0,0,0.10)",
  },
  cmdItem: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    padding: "8px 10px",
    background: "transparent",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "var(--font-family)",
  },
  cmdItemActive: {
    background: "var(--color-background)",
  },
  cmdUsage: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--color-primary)",
  },
  cmdDesc: {
    fontSize: 12,
    color: "var(--color-text-muted)",
  },
  settingsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  settingsTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--color-text-primary)",
  },
  settingsNote: {
    fontSize: 11,
    color: "var(--color-text-muted)",
    lineHeight: 1.4,
  },
  settingsEmbedRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
    paddingTop: 10,
    borderTop: "1px solid var(--color-border)",
  },
  settingsEmbedLabel: {
    fontSize: 12,
    color: "var(--color-text-muted)",
    flexShrink: 0,
  },
  settingsToggleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 24,
    marginTop: 12,
  },
  agentSwitchWrap: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  switchTrack: {
    position: "relative",
    width: 40,
    height: 24,
    padding: 2,
    borderRadius: 999,
    border: "none",
    background: "var(--color-border)",
    cursor: "pointer",
    flexShrink: 0,
    transition: "background 0.2s ease",
  },
  switchTrackOn: {
    background: "var(--color-text-primary)",
  },
  switchKnob: {
    display: "block",
    width: 20,
    height: 20,
    borderRadius: "50%",
    background: "var(--color-background)",
    boxShadow: "0 1px 3px rgba(0,0,0,0.25)",
    transition: "transform 0.2s ease",
  },

  proposalCard: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginTop: 12,
    padding: "12px 14px",
    borderRadius: 10,
    border: "1px solid color-mix(in srgb, var(--color-primary) 35%, var(--color-border))",
    background: "color-mix(in srgb, var(--color-primary) 5%, var(--color-surface))",
  },
  proposalHead: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  proposalKicker: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--color-primary)",
  },
  proposalType: {
    marginLeft: "auto",
    padding: "2px 8px",
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--color-text-muted)",
    background: "var(--color-background)",
    border: "1px solid var(--color-border)",
    borderRadius: 999,
  },
  proposalTopic: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.4,
    color: "var(--color-text-primary)",
  },
  proposalBrief: {
    margin: 0,
    fontSize: 12.5,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    color: "var(--color-text-muted)",
  },
  proposalMore: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    alignSelf: "flex-start",
    padding: 0,
    fontSize: 11,
    fontFamily: "var(--font-family)",
    color: "var(--color-primary)",
    background: "none",
    border: "none",
    cursor: "pointer",
  },
  proposalAgents: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  // Longhand border: proposalAgentUnknown overrides borderColor alone, and React
  // warns when a shorthand and its longhand are mixed across a rerender.
  proposalAgent: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 9px",
    fontSize: 11.5,
    fontWeight: 500,
    color: "var(--color-text-primary)",
    background: "var(--color-background)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--color-border)",
    borderRadius: 999,
  },
  proposalAgentUnknown: {
    color: "var(--color-warning, #d97706)",
    borderColor: "color-mix(in srgb, var(--color-warning, #d97706) 45%, var(--color-border))",
  },
  proposalCloser: {
    fontSize: 9.5,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--color-text-muted)",
  },
  proposalWarn: {
    display: "flex",
    alignItems: "flex-start",
    gap: 5,
    margin: 0,
    fontSize: 11.5,
    lineHeight: 1.5,
    color: "var(--color-warning, #d97706)",
  },
  proposalNote: {
    margin: 0,
    fontSize: 11.5,
    lineHeight: 1.55,
    color: "var(--color-text-muted)",
  },
  proposalCode: {
    padding: "1px 5px",
    fontSize: 11,
    fontFamily: "var(--font-mono, monospace)",
    background: "var(--color-background)",
    border: "1px solid var(--color-border)",
    borderRadius: 4,
  },
  proposalCodeStrong: {
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--color-text-primary)",
  },
  proposalLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    color: "var(--color-primary)",
    textDecoration: "none",
  },
  proposalPairRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  proposalPairInput: {
    width: 130,
    padding: "5px 9px",
    fontSize: 12,
    fontFamily: "var(--font-mono, monospace)",
    letterSpacing: "0.08em",
    color: "var(--color-text-primary)",
    background: "var(--color-background)",
    border: "1px solid var(--color-border)",
    borderRadius: 6,
    outline: "none",
  },
  proposalGhostBtn: {
    padding: "5px 12px",
    fontSize: 11.5,
    fontWeight: 500,
    fontFamily: "var(--font-family)",
    color: "var(--color-text-primary)",
    background: "var(--color-background)",
    border: "1px solid var(--color-border)",
    borderRadius: 6,
    cursor: "pointer",
  },
  proposalLaunch: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    alignSelf: "flex-start",
    padding: "7px 16px",
    fontSize: 12.5,
    fontWeight: 600,
    fontFamily: "var(--font-family)",
    color: "var(--color-background)",
    background: "var(--color-primary)",
    border: "1px solid var(--color-primary)",
    borderRadius: 7,
    cursor: "pointer",
  },
  proposalLaunchOff: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  proposalError: {
    margin: 0,
    fontSize: 11.5,
    lineHeight: 1.5,
    color: "var(--color-error, #dc2626)",
  },
};
