import type { CSSProperties } from "react";
import { COSMOS } from "./palette";

// Literal colours throughout: the graph is dark-only, so nothing here may inherit
// the app theme.

const card: CSSProperties = {
    background: COSMOS.panel,
    border: `1px solid ${COSMOS.border}`,
    borderRadius: 16,
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    boxShadow: "0 18px 48px rgba(0,0,0,0.55)",
    color: COSMOS.text,
};

// Longhand borders, not the `border` shorthand: the active variants below override
// borderColor, and mixing the two makes React drop the property on rerender.
const controlBase: CSSProperties = {
    font: "inherit",
    color: COSMOS.text,
    background: "rgba(148,163,201,0.09)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: COSMOS.border,
    borderRadius: 10,
    cursor: "pointer",
    transition: "background 0.15s ease, color 0.15s ease, border-color 0.15s ease",
};

export const styles: Record<string, CSSProperties> = {
    root: {
        position: "fixed",
        inset: 0,
        overflow: "hidden",
        background: COSMOS.background,
        color: COSMOS.text,
        fontFamily: "var(--font-family, system-ui)",
        fontSize: 13,
    },
    // Explicit edges rather than `inset`, because the mobile split overrides top and
    // bottom inline and a shorthand would fight it. The renderer is sized from this
    // element's own box, so the camera centres on what is actually visible.
    canvas: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 1 },

    nebulaOne: {
        position: "absolute",
        top: "-22%",
        left: "-12%",
        width: "62vw",
        height: "62vw",
        borderRadius: "50%",
        background: "radial-gradient(circle, rgba(58,38,138,0.30) 0%, rgba(26,17,64,0.13) 42%, transparent 70%)",
        filter: "blur(30px)",
        pointerEvents: "none",
        zIndex: 0,
    },
    nebulaTwo: {
        position: "absolute",
        right: "-16%",
        bottom: "-26%",
        width: "58vw",
        height: "58vw",
        borderRadius: "50%",
        background: "radial-gradient(circle, rgba(6,72,88,0.28) 0%, rgba(6,42,51,0.12) 45%, transparent 72%)",
        filter: "blur(34px)",
        pointerEvents: "none",
        zIndex: 0,
    },

    topBar: {
        position: "absolute",
        top: 14,
        left: 16,
        right: 16,
        zIndex: 10,
        display: "flex",
        alignItems: "center",
        gap: 10,
        // Wraps rather than pushing the controls off-screen on a narrow pane.
        flexWrap: "wrap",
        rowGap: 8,
        pointerEvents: "none",
    },
    topBarGroup: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "9px 14px",
        minWidth: 0,
        pointerEvents: "auto",
        ...card,
    },
    topBarSpacer: { flex: 1, minWidth: 0 },
    backBtn: {
        ...controlBase,
        width: 30,
        height: 30,
        display: "grid",
        placeItems: "center",
        color: COSMOS.muted,
        textDecoration: "none",
        flexShrink: 0,
    },
    titleStack: { display: "flex", flexDirection: "column", lineHeight: 1.15, minWidth: 0 },
    eyebrow: {
        fontSize: 9.5,
        fontWeight: 700,
        letterSpacing: "0.14em",
        textTransform: "uppercase",
        color: COSMOS.muted,
    },
    pageTitle: { fontSize: 14, fontWeight: 750, letterSpacing: "-0.02em", whiteSpace: "nowrap" },
    counts: { fontSize: 11, color: COSMOS.muted, whiteSpace: "nowrap", fontVariantNumeric: "tabular-nums" },
    staleDot: {
        display: "inline-flex",
        alignItems: "center",
        gap: 5,
        fontSize: 10.5,
        color: "#ffb545",
        whiteSpace: "nowrap",
    },
    iconBtn: {
        ...controlBase,
        width: 30,
        height: 30,
        display: "grid",
        placeItems: "center",
        color: COSMOS.muted,
        flexShrink: 0,
    },
    iconBtnActive: {
        color: "#dbe6ff",
        background: "rgba(107,167,255,0.20)",
        borderColor: "rgba(107,167,255,0.42)",
    },

    // The rails are rounded scroll viewports: a card taller than the rail then gets
    // clipped on a curve instead of ending in a hard flat edge. scrollbarColor is the
    // standard property: Chromium ignores ::-webkit-scrollbar once it is set, so the
    // dark thumb here is what actually renders.
    //
    // pointerEvents none on the rail itself, auto on its cards (.cosmos-rail > *):
    // the width clamps to calc(100vw - 32px), so on a phone a rail spans nearly the
    // whole viewport and its EMPTY area below the last card would otherwise swallow
    // every tap and drag meant for the canvas.
    leftRail: {
        position: "absolute",
        top: 68,
        left: 16,
        bottom: 92,
        width: "min(292px, calc(100vw - 32px))",
        zIndex: 9,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        overflowY: "auto",
        overflowX: "hidden",
        paddingRight: 4,
        borderRadius: 16,
        pointerEvents: "none",
        scrollbarWidth: "thin",
        scrollbarColor: "rgba(126,141,184,0.42) transparent",
    },
    rightRail: {
        position: "absolute",
        top: 68,
        right: 16,
        bottom: 92,
        width: "min(380px, calc(100vw - 32px))",
        zIndex: 9,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        overflowY: "auto",
        overflowX: "hidden",
        paddingRight: 4,
        borderRadius: 16,
        pointerEvents: "none",
        scrollbarWidth: "thin",
        scrollbarColor: "rgba(126,141,184,0.42) transparent",
    },

    // Phones get a docked region rather than a floating overlay. Two earlier attempts
    // failed for the same reason: whatever height the overlay took, the canvas stayed
    // window-sized, so flyTo centred the selected star in the middle of the WINDOW,
    // which is behind the panel. The dock claims real space and the canvas shrinks to
    // what is left, so the star it framed is centred in the visible half.
    mobileDock: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 12,
        display: "flex",
        flexDirection: "column",
        minHeight: 0,
        background: COSMOS.panel,
        borderTop: `1px solid ${COSMOS.border}`,
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        backdropFilter: "blur(18px)",
        WebkitBackdropFilter: "blur(18px)",
        boxShadow: "0 -18px 48px rgba(0,0,0,0.6)",
        color: COSMOS.text,
    },
    // One row replacing three overlapping things: the snap handle, the floating system
    // banner and a second close affordance.
    mobileDockHeader: {
        flexShrink: 0,
        display: "flex",
        alignItems: "center",
        gap: 8,
        padding: "9px 10px",
        borderBottom: `1px solid ${COSMOS.border}`,
    },
    mobileDockLabel: {
        flex: 1,
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        fontSize: 12,
        fontWeight: 650,
    },
    mobileDockBody: {
        flex: 1,
        minHeight: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        overflowY: "auto",
        overflowX: "hidden",
        padding: 10,
        scrollbarWidth: "thin",
        scrollbarColor: "rgba(126,141,184,0.42) transparent",
    },
    mobileGrip: {
        ...controlBase,
        width: 34,
        height: 28,
        display: "grid",
        placeItems: "center",
        color: COSMOS.muted,
        flexShrink: 0,
    },

    panel: { ...card, padding: "13px 14px", flexShrink: 0 },
    panelHeader: { display: "flex", alignItems: "flex-start", gap: 9, marginBottom: 11 },
    panelIcon: {
        width: 28,
        height: 28,
        borderRadius: 10,
        display: "grid",
        placeItems: "center",
        flexShrink: 0,
        color: "#9fb6e8",
        background: "rgba(107,167,255,0.13)",
        border: "1px solid rgba(107,167,255,0.24)",
    },
    panelTitle: { margin: 0, fontSize: 13, fontWeight: 750, letterSpacing: "-0.01em" },
    panelSubtle: { margin: "2px 0 0", fontSize: 11, lineHeight: 1.4, color: COSMOS.muted },
    sectionLabel: {
        margin: "13px 0 7px",
        fontSize: 9.5,
        fontWeight: 700,
        letterSpacing: "0.13em",
        textTransform: "uppercase",
        color: COSMOS.muted,
    },

    searchRow: {
        display: "flex",
        alignItems: "center",
        gap: 7,
        padding: "7px 9px",
        borderRadius: 11,
        background: "rgba(6,8,14,0.6)",
        border: `1px solid ${COSMOS.border}`,
    },
    searchInput: {
        flex: 1,
        minWidth: 0,
        background: "none",
        border: "none",
        outline: "none",
        font: "inherit",
        fontSize: 12.5,
        color: COSMOS.text,
    },
    clearBtn: {
        border: "none",
        background: "none",
        color: COSMOS.muted,
        cursor: "pointer",
        display: "grid",
        placeItems: "center",
        padding: 0,
    },
    resultList: { display: "flex", flexDirection: "column", gap: 2, marginTop: 7 },
    resultRow: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        padding: "6px 8px",
        borderRadius: 9,
        border: "none",
        background: "none",
        color: COSMOS.text,
        font: "inherit",
        fontSize: 12,
        textAlign: "left",
        cursor: "pointer",
        width: "100%",
    },
    resultRowActive: { background: "rgba(107,167,255,0.16)" },
    resultTitle: {
        flex: 1,
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    resultScore: { fontSize: 10, color: COSMOS.muted, fontVariantNumeric: "tabular-nums", flexShrink: 0 },

    chipRow: { display: "flex", flexWrap: "wrap", gap: 6 },
    chip: {
        ...controlBase,
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        padding: "5px 9px",
        borderRadius: 999,
        fontSize: 11.5,
        fontWeight: 600,
        color: COSMOS.muted,
    },
    chipActive: { color: COSMOS.text, background: "rgba(148,163,201,0.20)", borderColor: COSMOS.borderStrong },
    chipDot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },

    lensGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6 },
    lensBtn: {
        ...controlBase,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 6,
        padding: "7px 8px 7px 10px",
        fontSize: 11.5,
        fontWeight: 650,
        color: COSMOS.muted,
        textAlign: "left",
    },
    keycap: {
        display: "inline-grid",
        placeItems: "center",
        minWidth: 16,
        height: 16,
        padding: "0 3px",
        flexShrink: 0,
        borderRadius: 5,
        fontSize: 9,
        fontWeight: 700,
        fontFamily: "var(--font-mono, ui-monospace, monospace)",
        color: COSMOS.muted,
        background: "rgba(6,8,14,0.55)",
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: COSMOS.border,
    },
    lensBtnActive: {
        color: COSMOS.text,
        background: "rgba(107,167,255,0.18)",
        borderColor: "rgba(107,167,255,0.40)",
    },
    lensHint: { fontSize: 9.5, fontWeight: 500, opacity: 0.72, lineHeight: 1.3 },
    legendRow: { display: "flex", alignItems: "center", gap: 7, fontSize: 11, color: COSMOS.muted, padding: "3px 0" },

    statsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 7, marginTop: 10 },
    statCard: {
        padding: "8px 9px",
        borderRadius: 11,
        background: "rgba(6,8,14,0.5)",
        border: `1px solid ${COSMOS.border}`,
        display: "flex",
        flexDirection: "column",
        gap: 2,
    },
    statValue: { fontSize: 16, fontWeight: 750, fontVariantNumeric: "tabular-nums", letterSpacing: "-0.02em" },
    statLabel: { fontSize: 9.5, color: COSMOS.muted, textTransform: "uppercase", letterSpacing: "0.08em" },

    switchRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 10,
        padding: "5px 0",
        fontSize: 12,
        color: COSMOS.text,
    },
    switchLabel: { display: "flex", alignItems: "center", gap: 7, color: COSMOS.muted, fontSize: 11.5 },
    switch: {
        ...controlBase,
        width: 38,
        height: 21,
        borderRadius: 999,
        padding: 2,
        display: "flex",
        alignItems: "center",
        flexShrink: 0,
    },
    switchOn: { background: "rgba(107,167,255,0.42)", borderColor: "rgba(107,167,255,0.55)" },
    switchKnob: {
        width: 15,
        height: 15,
        borderRadius: "50%",
        background: COSMOS.text,
        transition: "transform 0.16s ease",
    },

    sliderRow: { display: "flex", flexDirection: "column", gap: 4, padding: "5px 0" },
    sliderHead: { display: "flex", justifyContent: "space-between", fontSize: 11, color: COSMOS.muted },
    slider: { width: "100%", accentColor: "#6ba7ff" },

    listRow: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        width: "100%",
        padding: "7px 8px",
        borderRadius: 10,
        border: "none",
        background: "rgba(6,8,14,0.45)",
        color: COSMOS.text,
        font: "inherit",
        fontSize: 12,
        textAlign: "left",
        cursor: "pointer",
    },
    listRowLead: {
        width: 20,
        fontSize: 10,
        color: COSMOS.muted,
        fontVariantNumeric: "tabular-nums",
        flexShrink: 0,
    },
    listRowMeta: { fontSize: 10.5, color: COSMOS.muted, flexShrink: 0, fontVariantNumeric: "tabular-nums" },
    listStack: { display: "flex", flexDirection: "column", gap: 4 },

    pagePanelTitle: { margin: 0, fontSize: 15, fontWeight: 750, letterSpacing: "-0.02em", lineHeight: 1.25 },
    pagePath: {
        fontSize: 10.5,
        color: COSMOS.muted,
        wordBreak: "break-all",
        fontFamily: "var(--font-mono, ui-monospace, monospace)",
    },
    badgeRow: { display: "flex", flexWrap: "wrap", gap: 5, marginTop: 8 },
    badge: {
        display: "inline-flex",
        alignItems: "center",
        gap: 4,
        padding: "3px 7px",
        borderRadius: 7,
        fontSize: 10,
        fontWeight: 650,
        letterSpacing: "0.02em",
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: "transparent",
    },
    markdown: {
        maxHeight: 300,
        overflowY: "auto",
        fontSize: 12.5,
        lineHeight: 1.55,
        color: "#c9d2e8",
        marginTop: 10,
        paddingRight: 6,
        scrollbarWidth: "thin",
        scrollbarColor: "rgba(126,141,184,0.42) transparent",
    },
    editArea: {
        width: "100%",
        minHeight: 260,
        marginTop: 10,
        padding: 10,
        borderRadius: 11,
        background: "rgba(4,6,11,0.75)",
        border: `1px solid ${COSMOS.border}`,
        color: COSMOS.text,
        font: "inherit",
        fontFamily: "var(--font-mono, ui-monospace, monospace)",
        fontSize: 12,
        lineHeight: 1.5,
        resize: "vertical",
        outline: "none",
        scrollbarWidth: "thin",
        scrollbarColor: "rgba(126,141,184,0.42) transparent",
    },
    actionRow: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 11 },
    action: { ...controlBase, display: "inline-flex", alignItems: "center", gap: 6, padding: "6px 10px", fontSize: 11.5, fontWeight: 650 },
    actionPrimary: {
        color: "#08131f",
        background: "#8fc2ff",
        borderColor: "#8fc2ff",
    },
    actionDanger: {
        color: "#ffb3c0",
        background: "rgba(255,84,112,0.14)",
        borderColor: "rgba(255,84,112,0.38)",
    },

    timelineWrap: {
        position: "absolute",
        left: "50%",
        bottom: 18,
        transform: "translateX(-50%)",
        zIndex: 10,
        width: "min(760px, calc(100vw - 40px))",
        padding: "11px 15px",
        display: "flex",
        alignItems: "center",
        gap: 12,
        ...card,
    },
    timelineMeta: { display: "flex", flexDirection: "column", gap: 1, minWidth: 108, flexShrink: 0 },
    timelineDate: { fontSize: 12.5, fontWeight: 700, fontVariantNumeric: "tabular-nums" },
    timelineNote: { fontSize: 9.5, color: COSMOS.muted },

    toast: {
        position: "absolute",
        left: "50%",
        bottom: 96,
        transform: "translateX(-50%)",
        zIndex: 20,
        padding: "9px 15px",
        borderRadius: 999,
        fontSize: 12,
        maxWidth: "min(520px, calc(100vw - 40px))",
        textAlign: "center",
        ...card,
    },
    banner: {
        position: "absolute",
        top: 68,
        left: "50%",
        transform: "translateX(-50%)",
        zIndex: 10,
        display: "flex",
        alignItems: "center",
        gap: 9,
        padding: "7px 12px",
        fontSize: 11.5,
        // width:max-content WITH a cap, not a cap alone. Anchored at left:50% the box is
        // shrink-to-fit, and a nowrap child's minimum content width then wins over the
        // available space, which is how it ended up hanging off the right edge. Giving
        // the width a definite basis is also what makes the label's ellipsis fire.
        width: "max-content",
        maxWidth: "min(560px, calc(100vw - 32px))",
        ...card,
    },
    bannerLabel: {
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    overlay: {
        position: "absolute",
        inset: 0,
        zIndex: 30,
        display: "grid",
        placeItems: "center",
        background: "rgba(5,6,10,0.72)",
        color: COSMOS.muted,
        fontSize: 13,
        gap: 10,
    },
    empty: { fontSize: 11.5, lineHeight: 1.5, color: COSMOS.muted, padding: "8px 2px" },
    contextMenu: {
        position: "absolute",
        zIndex: 40,
        minWidth: 186,
        padding: 5,
        display: "flex",
        flexDirection: "column",
        gap: 2,
        ...card,
    },
    contextItem: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        padding: "7px 9px",
        borderRadius: 8,
        border: "none",
        background: "none",
        color: COSMOS.text,
        font: "inherit",
        fontSize: 12,
        textAlign: "left",
        cursor: "pointer",
        width: "100%",
    },
};
